# Generated by Django 2.2.5 on 2020-04-14 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_auto_20200414_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='author',
        ),
    ]
